package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class FinalPageController {
	@FXML
	private Label ordernumberLabel;
	@FXML
	private Label deliveryagentLabel;
	@FXML
	private Label arrivinginLabel;
	@FXML
	private Label pointsearnedLabel;
	@FXML
	private Button logout;
	@FXML
	private Label mb;

	// Event Listener on Button[#logout].onAction
	@FXML
	public void logout(ActionEvent event) {
		// TODO Autogenerated
	}
}
